<?php 

//please use the last entry to copy-paste more labels.

Translator::loadTranslation('en', array(
	'admin_title'			=>	'Customer Comment Center: Administration',
	'admin_login'			=>	'Administrator Login',
 	'admin_subtitle'		=> 'Comment Center &#153 - Admin Module.',
	'all_title'				=> 'Customer Comment Center',
	'all_language'			=>	'Language',
 	'title_launchpad'		=> 'Customer Comment Center Launchpad',
 	'index_subtitle'		=> 'Customer Comment Center&#153 - Home page ',
 	'index_byline'			=> 'Comment Center(tm) would help your customers provide you feedback without any hassle for them.',
	'all_advert'			=> 'Insert an advertisement here',
	'all_banner'			=> 'Place a banner here if you have any else disable this section.',
	'index_what_ccenter'	=> 'What is a Customer Comment Center &#153?',
	'index_ccenter_defn'	=> 'It is an internet based utility which can been setup by a business with consumer touchpoints. This is a great way for your consumers to provide you a quick feedback while they are still on your premise. Or you can let them access your Customer Comment Center using their handheld computers.',
	'index_exist_user'		=> 'Existing Customers: Login to manage your Customer Comment Centers.',
	'index_new_user'		=> 'New customers can register themselves here.',
	'all_login'				=>	'Login',
	'index_label_login'		=> 'Login ID',
	'index_label_password'	=> 'Password',
	'index_label_repeat_password'	=> 'Password',
	'index_admin_login'		=> 'Click here if you are the site administrator.',
	'list_ccenter_header' 	=> 'Click on a row to view or launch its comment center ',
	'list_create_new'	 	=> 'Click here to create a new Customer Comment Center ',
	'list_tabhead_serial'	=>	'S.No.',
	'list_tabhead_logo'		=>	'Logo filename',
	'list_tabhead_display'	=>	'Display Title',
	'list_tabhead_toemail'	=>	'To Email',
	'list_tabhead_ccemail'	=>	'CC Email',
	'list_tabhead_action'	=>	'Actions',
	'list_tabhead_lang'		=>	'Lang',
	'cc_first_name'			=>	'First Name',
	'cc_last_name'			=>	'Last Name',
	'cc_phone'				=>	'Phone',
	'cc_email'				=>	'Email',
	'cc_comment'			=>	'Comment',
	'cc_enter_comment'		=>	'Enter your comments ...',
	'cc_twitter_launch' 	=>	'Press to start (real time chat)',
	'pro_label_org_name'	=>	'Org Name',
	'pro_label_address'		=>	'Address',
	'pro_label_contact'		=>	'Contact Person',
	'pro_label_email'		=>	'Contact Email',
	'pro_label_phone'		=>	'Phone',
	'ccdel_title'			=>	'Comment Center Management - Delete',
	'ccdel_succ_msg'		=>	'The client details have been removed from the database. Follow the link to go back.',
	'ccnew_language'		=>	'Site Language',
	'ccnew_english'			=>	'English',
	'ccnew_french'			=>	'French',
	'ccsave_succ_msg'		=>	'The comment center has been created/modified, however it is not yet active. Admin will communicate on your email upon activation. It may take 48 business hours. Please bear with us.',
	'ccsave_fail_msg' 		=> 	'The comment center has been created however the email notification to the admin has failed. Contact the admin directly for having it activated. It may take 48 business hours. Please bear with us.',
	'all_go_back'			=>	'Go back',
	'all_go_back2main'		=>	'Click here to return to the main page.',
	'ccmod_header'			=>	'Modify Details of a Comment Center',
	'ccnew_header'			=>	'Create a New Comment Center',
	'saveprofile_succ_msg'	=>  'You profile has been created. Admin will communicate on your email with a user name and password. You can access the account using the same.',
	'saveprofile_fail_msg'	=>	'You profile has been created however the email notification to the admin has failed. Contact the admin directly. Admin will communicate on your email with a user name and password. You can access the account using the same.',
	'saveprofile_upd_msg'	=>	'You profile has been updated.',
	'range_desc'			=>	 'insert the text here. use this line to copy & paste. leave this line untouched as the last line',
));

?>